command=C\:\\Users\\ForgotLJ\\.conda\\envs\\pytorch_env\\python.exe D\:\\Project\\STS\\sts_agent\\scripts\\communication-relay.py --host 127.0.0.1 --port 51234 --trace D\:\\Project\\STS\\sts_agent\\real_game_traces\\communication.jsonl --log D\:\\Project\\STS\\sts_agent\\real_game_traces\\relay.log
runAtGameStart=true
maxInitializationTimeout=30
verbose=false
